#!/bin/bash

SSL_KEY_PASS=$(cat "/etc/schema-registry/secrets/key.credentials")
SSL_KEYSTORE_LOCATION=/etc/schema-registry/secrets/server.keystore.bcfks
SSL_KEYSTORE_PASS=$(cat "/etc/schema-registry/secrets/keystore.credentials")
SSL_TRUSTSTORE_LOCATION=/etc/schema-registry/secrets/server.truststore.bcfks
SSL_TRUSTSTORE_PASS=$(cat "/etc/schema-registry/secrets/truststore.credentials")

JAVA_OPTS="$JAVA_OPTS \
    -Djavax.net.ssl.keyStore=$SSL_KEYSTORE_LOCATION \
    -Djavax.net.ssl.keyStorePassword=$SSL_KEYSTORE_PASS \
    -Djavax.net.ssl.keyStoreType=BCFKS \
    -Djavax.net.ssl.keyStoreProvider=BCFIPS \
    -Djavax.net.ssl.trustStore=$SSL_TRUSTSTORE_LOCATION \
    -Djavax.net.ssl.trustStorePassword=$SSL_TRUSTSTORE_PASS \
    -Djavax.net.ssl.trustStoreType=BCFKS \
    -Djavax.net.ssl.trustStoreProvider=BCFIPS \
    -Djdk.tls.server.protocols=TLSv1.2"

export SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SSL
export SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD=$SSL_KEY_PASS
export SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION=$SSL_KEYSTORE_LOCATION
export SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD=$SSL_KEYSTORE_PASS
export SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_TYPE=BCFKS
export SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION=$SSL_TRUSTSTORE_LOCATION
export SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD=$SSL_TRUSTSTORE_PASS
export SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_TYPE=BCFKS
export SCHEMA_REGISTRY_KAFKASTORE_SSL_ENABLED_PROTOCOLS=TLSv1.2

export SCHEMA_REGISTRY_SSL_KEY_PASSWORD=$SSL_KEY_PASS
export SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION=$SSL_KEYSTORE_LOCATION
export SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD=$SSL_KEYSTORE_PASS
export SCHEMA_REGISTRY_SSL_KEYSTORE_TYPE=BCFKS
export SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION=$SSL_TRUSTSTORE_LOCATION
export SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD=$SSL_TRUSTSTORE_PASS
export SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE=BCFKS
export SCHEMA_REGISTRY_SSL_CLIENT_AUTHENTICATION=REQUIRED

exec /etc/confluent/docker/run